POST http://localhost:3001/api/transactions/debit
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhc2hmaXJlZEBnbWFpbC5jb20iLCJpZCI6IjYwYzQ3NWE2ZTE5YzZkMjEyMTY3ZmU1MiIsImlhdCI6MTYyMzQ5NzQ5NX0.D2sopnqN213xcoCl5ysoEIWAzHwuDKMVBcUFPD5otwU

{
  "transactionAccount": "09013889801",
  "amount": 15000
}