PUT http://localhost:3001/api/users/60c3565ff237f811025d1c58
Content-Type: application/json

{
  "name":"Damilola Faseun",
  "email":"fashfired@gmail.com",
  "number":"09017755801",
  "balance": 2000
}
